server:
  port: 10010
spring:
  application:
    name: Gateway
  cloud:
    nacos:
      server-addr: 192.168.32.194:3301
      username: nacos
      password: nacos
      discovery:
        cluster-name: HZ
        namespace: ef5c761c-3893-4e7d-b4ba-815e4d3f880c
    gateway:
      routes:
        - id: User-Server
          uri: lb://UserServer
          predicates:
            - Path=/user/**
#          filters:
#            - AddRequestHeader=Truth,ZNY
        - id: Order-Server
          uri: lb://OrderServer
          predicates:
            - Path=/order/**
      default-filters:
        - AddRequestHeader=Truth,ZNY